#!/usr/bin/env python3
# Copyright (c) 2024 Damien Ciabrini
# This file is part of ngdevkit
#
# ngdevkit is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ngdevkit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with ngdevkit.  If not, see <http://www.gnu.org/licenses/>.

"""soundtool.py - generate command data for z80 and m68k."""

import argparse
import re
import sys
import yaml
import glob
import os

VERBOSE = False


def error(s):
    sys.exit("error: " + s)


def dbg(s):
    if VERBOSE:
        print(s, file=sys.stderr)

def mkid(x):
    return re.sub(r"\W|^(?=\d)", "_", x).lower()

def generate_sound_desc():
    desc=[]

    for f in glob.iglob("./music/*.fur", recursive=True):
        if not os.path.isfile(f):
            continue
        uri='file://'+f
        name=mkid(os.path.splitext(os.path.basename(f))[0])
        desc.append({'nss': {'name': name, 'uri': uri}})

    for f in glob.iglob("./adpcma/**", recursive=True):
        if not os.path.isfile(f):
            continue
        sfxtype=''
        if 'adpcma' in f.lower():
            sfxtype = 'adpcm_a'
        elif 'adpcmb' in f.lower():
            sfxtype = 'adpcm_b'
        if not sfxtype:
            dbg('unknown sfx type: %s'%f)
            continue
        uri='file://'+f
        name=mkid(os.path.splitext(os.path.basename(f))[0])
        desc.append({sfxtype: {'name': name, 'uri': uri}})

    return desc



def parse_cmd(i):
    k=list(i.keys())[0]
    v=i[k]
    stype='music' if k == 'nss' else k
    return stype, v


def dump_m68k_commands(desc, f):
    print("/* macros definitions for music and sfx commands", file=f)
    print(" * generated by soundtool.py (ngdevkit)", file=f)
    print(" */", file=f)
    print('', file=f)

    print('#ifndef _SND_CMD_BASE_GENERATED', file=f)
    print('#define _SND_CMD_BASE_GENERATED 4', file=f)
    print('#endif', file=f)
    print('', file=f)
    for n, i in enumerate(desc):
        stype, data = parse_cmd(i)
        name='SND_%s_%s'%(stype.upper(),data['name'].upper())
        print('#define %s (_SND_CMD_BASE_GENERATED + %d)'%(name,n), file=f)


def dump_z80_commands(desc, f):
    def print_jp_cmd(stype, data):
        stype='sfx' if 'adpcm' in stype else stype
        name=data['name']
        print('        jp      %s_%s'%(stype,name), file=f)

    def print_music_cmd(data):
        name=data['name']
        print('play_%s::'%name, file=f)
        print('        ld      bc, #%s_instruments'%name, file=f)
        print('        ld      de, #%s_nss_stream'%name, file=f)
        print('        call    snd_stream_play', file=f)
        print('        ret', file=f)
        print('', file=f)

    def print_sfx_cmd(stype, data):
        name=data['name']
        channel=data.get('channel', 6)-1
        ucname=name.upper()
        print('sfx_%s::'%name, file=f)
        print('        ld      ix, #sfx_%s_data'%name, file=f)
        print('        call    snd_%s_play'%stype, file=f)
        print('        ret', file=f)
        print('sfx_%s_data:'%name, file=f)
        print('        .db     %s_START_LSB, %s_START_MSB ; start>>8 in VROM'%(ucname,ucname), file=f)
        print('        .db     %s_STOP_LSB, %s_STOP_MSB   ; stop>>8 in VROM'%(ucname,ucname), file=f)
        print('        .db     0x%02x ; channel'%channel, file=f)
        print('        .db     0xda ; l/r output + volume', file=f)
        print('        .db     0x%02x ; channel (bit)'%(1<<channel), file=f)
        print('', file=f)
        
    print(";;; macros definitions for music and sfx commands", file=f)
    print(";;; generated by soundtool.py (ngdevkit)", file=f)
    print('', file=f)

    print('        .macro generated_commands_jmptable_entries', file=f)
    for i in desc:
        stype, data = parse_cmd(i)
        print_jp_cmd(stype, data)
    print('        .endm', file=f)

    print('', file=f)

    print('        .macro generated_commands_implementation', file=f)
    for i in desc:
        stype, data = parse_cmd(i)
        if stype == 'music':
            print_music_cmd(data)
        if 'adpcm' in stype:
            print_sfx_cmd(stype, data)
    print('        .endm', file=f)


def main():
    # Generate sound driver description from files on disk
    desc = generate_sound_desc()

    # save sound driver description
    # with open('sdd.yaml', 'w') as f:
    #     print(yaml.dump(desc), file=f)
    # sys.exit(0)
    
    # load sound driver description from yaml
    # with open('sdd.yaml', 'r') as f:
    #     desc=yaml.loads(f.read())
    # print(desc)
    # sys.exit(0)

    # generate z80 macros
    with open('generated_commands.inc','w') as f:
        # dump_z80_commands(desc, sys.__stdout__)
        dump_z80_commands(desc, f)
    
    # generate m68k macros
    with open('snd_commands.h','w') as f:
        # dump_m68k_commands(desc, sys.__stdout__)
        dump_m68k_commands(desc, f)


if __name__ == "__main__":
    main()
