;;;
;;; Copyright (c) 2020-2024 Damien Ciabrini
;;; This file is part of ngdevkit-examples
;;;
;;; ngdevkit is free software: you can redistribute it and/or modify
;;; it under the terms of the GNU Lesser General Public License as
;;; published by the Free Software Foundation, either version 3 of the
;;; License, or (at your option) any later version.
;;;
;;; ngdevkit is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU Lesser General Public License for more details.
;;;
;;; You should have received a copy of the GNU Lesser General Public License
;;; along with ngdevkit.  If not, see <http://www.gnu.org/licenses/>.
;;;

;;; user-specific commands to link this ROM's sound driver
;;; ------------------------------------------------------
        .include "helpers.inc"

        ;; macros for sample offsets in VROM
        ;; generated by vromtool
        .include "samples.inc"

        ;; macros for music and sfx commands for this ROM
        ;; generated by soundtool
        .include "snd_commands.inc"

        .area   CODE


;;; The ROM must provide a jump table to all sound commands
;;; The jump table includes command 01 and 03 which are
;;; implemented by nullsound
;;; The other commands are specific to this ROM
;;;

cmd_jmptable::
        ;; common/reserved sound commands
        jp      snd_command_unused
        jp      snd_command_01_prepare_for_rom_switch
        jp      snd_command_unused
        jp      snd_command_03_reset_driver
        ;; the following sound commands are up to the user
        jp      stream_stop
        jp      stream_volume_down
        jp      stream_volume_up
        jp      volume_fade_out
        ;; the remaining commands to play music and sfx commands for this ROM
        ;; generated by soundtool
        generated_commands_jmptable_entries
        ;; complete unused sound commands (up to all 256 possible commands)
        init_unused_cmd_jmptable

        ;; every custom sound command for this ROM are implemented below
        ;; (no customization for this ROM)

        ;; inline all the remaining code and config for all the music
        ;; and sfx commands for this ROM
        generated_commands_implementation
